# Material to drop on death: (SCUTE, TURTLE_SHELL / TURTLE_HELMET, or SEAGRASS)
drop_material: SCUTE
# Change sea_grass to new material (works with looting)
change_turtles_drops: false
# drop probability per roll; examples: 1.0 is 100%, 0.5 is 50%
drop_probability: 0.7
# roll_count = looting_level + 1
drop_roll_maximum: 1
# maximum amount of drops from a single kill; set to -1 for no maximum
total_maximum: 1

#enable helmet changes
enable_diamond_turtle_helmets: true
#enables both netherite and diamond helmets
enable_netherite_turtle_helmets: true

# Drop scute when growing up
enable_scute_on_grow_up: true
# Minimum amount dropped when loosing scute
minimum_drop_quantity: 1
# Maximum amount dropped when loosing scute
maximum_drop_quantity: 3

# Return home on grow_up
return_home_on_grow_up: false
# Only molt when arriving at home (force enables "Return home on grow_up")
molt_when_return_home: false